[tool.poetry]
name = "roop"
version = "0.1.0"
description = ""
authors = ["Diven <aboutmydreams@163.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
numpy = "1.23.5"
opencv-python = "4.8.0.74"
onnx = "1.14.0"
insightface = "0.7.3"
psutil = "5.9.5"
tk = "^0.1.0"
customtkinter = "5.2.0"
tkinterdnd2 = "0.3.0"
tkinterdnd2-universal = "1.7.3"
pillow = "10.0.0"
torch = "^2.0.1"
onnxruntime = "^1.15.1"
tensorflow = "^2.13.0"
opennsfw2 = "^0.10.2"
protobuf = "^4.23.4"
tqdm = "^4.65.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
